name: millie-front-deploy

on:
  push:
    branches: ["main"]
  
jobs:
  build:
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node-version }}
      
      - name: Install Dependencies
        run: npm install
        
      - name: Build Project
        run: ./node_modules/react-scripts/bin/react-scripts.js build build
        env: 
          CI: false
      
      - name: Deploy S3
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRETE_ACCESS_KEY: ${{ secrets.AWS_SECRETE_KEY }}
        run: 
          aws s3 sync --delete --region us-east-1 build s3://inflearn-aws-s3
